### ISSUE TITLE
Hello there is no problem, rather a question.

### ISSUE THREAD

**Issue by kotana** [rianadon/timer-bar-card#5]
How can I use this identity attribute?
Thanks in advance.
![image](https://user-images.githubusercontent.com/760382/123125410-c7d08f00-d448-11eb-9bed-7f9a0165001d.png)

**Comment by rianadon** [comment]
It should work by providing only the duration:

```
type: custom:timer-bar-card
entities:
  - binary_sensor.irrigation_unlimited_c1_m
duration: { attribute: current_duration }
```

Let me know if this doesn't work / is inaccurate. The `time_remaining` in your screenshot looks of use, but I don't know how often it is updated.

**Comment by kotana** [comment]
Unfortunately it does not work.
It just shows me the current status. on or off.
![image](https://user-images.githubusercontent.com/760382/123276942-f19bbb80-d505-11eb-8c95-5edcf4e495fa.png)
![image](https://user-images.githubusercontent.com/760382/123276953-f52f4280-d505-11eb-8ce4-d317d564234f.png)

**Comment by rianadon** [comment]
Double check you are on version 1.3! I've been adding the features to make this work very recently.

Otherwise, your configuration looks correct.

**Comment by kotana** [comment]
Hi,
I now have version V1.4
Unfortunately it does not work.
Only the status is displayed.

**Comment by rianadon** [comment]
I'm sorry I really have no idea why this is not working.

I've released another version that's added a debugging mode for showing what the card thinks the duration & time remaining are. It would be helpful if you could upgrade again, add `debug: true` to your configuration, and paste/screenshot the debugging information.

Not that I think it would make much difference to the problem at hand, but since your card has a `current_start` attribute, you could supply this config:
```yaml
type: custom:timer-bar-card
entities:
  - binary_sensor.irrigation_unlimited_c1_m
duration: { attribute: current_duration }
start_time: { attribute: current_start }
``` 

Thanks for spending time on this!

**Comment by kotana** [comment]
Here is a screenshot of the debug
![image](https://user-images.githubusercontent.com/760382/123413645-4fd2a800-d5b3-11eb-965b-ef2db63d2983.png)

Oh by the way, dark theme does not work properly, the font cannot recognize mn in (debug mode)
![image](https://user-images.githubusercontent.com/760382/123413660-53fec580-d5b3-11eb-89dd-7ce3df19c32e.png)

**Comment by rianadon** [comment]
Aha! I see the problem! Looks like I have a bug duration didn't add correctly to compute the time remaining (`-22.785 seconds` + `0:01:00` duration, or `60 seconds` = `37.215 seconds`, not `-22.7850:01:00`. 

I've fixed this problem in v1.6. Hopefully this one should solve the problem!

**Comment by kotana** [comment]
Hi,
so far everything works.
But there is still a problem with the filter or display.

filter is true ( everything is ok, i started nothing )
![image](https://user-images.githubusercontent.com/760382/123505397-2ec79100-d65f-11eb-9fcc-10af3c0c1c02.png)

filter is true ( everything is ok, started the process )
![image](https://user-images.githubusercontent.com/760382/123505438-62a2b680-d65f-11eb-9e25-bb33a82c992f.png)

filter is true ( everything is ok, process stopped, but the time continues. )
![image](https://user-images.githubusercontent.com/760382/123505455-7cdc9480-d65f-11eb-9c5c-de60ce0cb018.png)
![image](https://user-images.githubusercontent.com/760382/123505483-9e3d8080-d65f-11eb-811b-1cc25d7d89be.png)

**Comment by rianadon** [comment]
Yikes. I know what the problem is.

For weekdays, timers, and next_trigger, did you have in mind any designs of how these should be shown?

**Comment by kotana** [comment]
simple text is sufficient for weekdays.

Timers: think also as text

next_triger: as a bar

**Comment by rianadon** [comment]
Hmm I can't visualize how I could fit this all into one row, unless you'd like to draw me something.

For the text parts, A [template sensor](https://www.home-assistant.io/integrations/template/) might fulfill your needs. Something like:

```yaml
template:
  - sensor:
    - name: "Times"
       state: >
         {% set weekdays = state_attr('switch.schedule_nachsaat_4x_taglich, 'weekdays') %}
         {% set times = state_attr('switch.schedule_nachsaat_4x_taglich, 'times') %}
         
         {{ weeekdays }} at {{ times }}
```

For `next_trigger`, from when would the bar start counting down? (that is, if `next_trigger` is the end time, what would be the start time?) You could set only `end_time`, which means the card would use the time last changed as the start time, but I don't know if that's what you want.

**Comment by luixal** [comment]
Thanks for this issue, I'm using Irrigation Unlimited integration too and [this worked like a charm](https://github.com/rianadon/timer-bar-card/issues/5#issuecomment-868267817). Maybe it would be a good idea to add it to the readme near the use with openSprinkler ;)

**Comment by rianadon** [comment]
Thanks for the suggestion! I added a link to the readme.

**Comment by luixal** [comment]
I still have to polish some things on the irrigation unlimited side, such as how to get total irrigation remaining time (instead of per zone) so I can añso show a timer bar for the whole irrigation sequence.

If you like, I can make a PR with example and how to set it up :)

Just let me know if you prefer me adding a section linked in the list in the readme, or should I add a new md file and link it in the readme.

**Comment by rianadon** [comment]
Yes, please! A PR with your examples would be much appreciated. If it's short I'd prefer the readme, otherwise I'd prefer you make another issue with the [integration doc ](https://github.com/rianadon/timer-bar-card/issues?q=is%3Aissue+label%3A%22integration+doc%22) label and link it to the readme. That way there's a spot for anyone who has questions to ask them.

Dealing with arrays is not something I expect to ever support in the card. If you'd like to avoid creating another sensor, maybe the [config template card](https://github.com/iantrich/config-template-card) would help you pass in the value. I've never played with the card before, but it would be really awesome to see if it works.
